services:
  traefik:
    image: traefik:v3.6.2
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-net
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-net"
      - "--entryPoints.web.address=:80"
      # TLS
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      # Let's Encrypt configuration
      - "--certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt

  leantime_db:
    image: mysql:8.4
    container_name: mysql_leantime
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    env_file: ./.env                                        # Environment file with settings
    networks:
      - leantime-net
    command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  leantime_redis:
    image: redis:latest
    container_name: redis_leantime
    restart: unless-stopped
    networks:
      - leantime-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - redis_data:/data

  leantime:
    image: leantime/leantime:${LEAN_VERSION:-latest}
    restart: unless-stopped
    env_file: ./.env                                        # Environment file with settings
    # Add security options
    security_opt:
      - no-new-privileges:true
    # Add capabilities
    cap_add:
      # - CAP_NET_BIND_SERVICE
      - CAP_CHOWN
      - CAP_SETGID
      - CAP_SETUID
    networks:
      - leantime-net
      - traefik-net
    volumes:
      - public_userfiles:/var/www/html/public/userfiles     # Volume to store public files, logo etc
      - userfiles:/var/www/html/userfiles                   # Original volume name for compatibility
      - plugins:/var/www/html/app/Plugins                   # Plugin storage
      - logs:/var/www/html/storage/logs
    labels:
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.leantime.rule=Host(\"${LEAN_HOST_NAME}\")"
      - "traefik.http.routers.leantime.entrypoints=websecure"
      - "traefik.http.routers.leantime.service=leantime"
      # Service
      - "traefik.http.services.leantime.loadbalancer.server.port=8080"
      # TLS
      - "traefik.http.routers.leantime.tls=true"
      - "traefik.http.routers.leantime.tls.certresolver=le"
    depends_on:
      leantime_db:
        condition: service_healthy
      leantime_redis:
        condition: service_healthy

  # Add a helper container for volume permissions
  # Run via docker compose --profile mysql_helper up -d
  mysql_helper:
    image: mysql:8.4
    command: chown -R mysql:mysql /var/lib/mysql
    volumes:
      - db_data:/var/lib/mysql
    user: root
    profiles: [ "helper" ]

volumes:
  db_data:
  redis_data:
  userfiles:                                               # New volume for public files
  public_userfiles:
  plugins:
  logs:
  letsencrypt:

networks:
  leantime-net:
  traefik-net:
